package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTDefine extends ASTStatement {
  String var;
  ASTFracExp valueExp;

  public ASTDefine (String var,ASTFracExp valueExp) {
    this.var = var;
    this.valueExp = valueExp;
  }

  public String getVar() {
    return var;
  }

  public ASTFracExp getValueExp() {
    return valueExp;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTDefine(this, state);
  }

}
