package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;
import fractal.values.FractalValue;

/**
  Class ASTExpLit.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTExpLit extends ASTExp {
  FractalValue value;

  public ASTExpLit (FractalValue value) {
    this.value = value;
  }

  public FractalValue getValue() {
    return value;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTExpLit(this, state);
  }

}
