package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTFracVar.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTFracVar extends ASTFracExp {
  String var;

  public ASTFracVar (String var) {
    this.var = var;
  }

  public String getVar() {
    return var;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTFracVar(this, state);
  }

}
