package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTFracCompose.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTFracCompose extends ASTFracExp {
  ASTFracExp first;
  ASTFracExp second;

  public ASTFracCompose (ASTFracExp first,ASTFracExp second) {
    this.first = first;
    this.second = second;
  }

  public ASTFracExp getFirst() {
    return first;
  }

  public ASTFracExp getSecond() {
    return second;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTFracCompose(this, state);
  }

}
