package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
 * Class ASTProgram. Intermediate representation class autogenerated by
 * CS34Q semantic generator. Created on Sat Oct 12 03:13:16 2013
 */
public class ASTProgram extends ASTNode {

    ASTStmtSequence statements;

    public ASTProgram(ASTStmtSequence statements) {
        this.statements = statements;
    }

    /**
     *
     * @return The sequence of statements making up this program
     */
    public ASTStmtSequence getStatements() {
        return statements;
    }

    @Override
    public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
        return v.visitFractalProgram(this, state);
    }
}
