package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTSelf.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTSelf extends ASTStatement {
  ASTExp length;

  public ASTSelf (ASTExp length) {
    this.length = length;
  }

  public ASTExp getLength() {
    return length;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTSelf(this, state);
  }

}
