/* The following code was generated by JFlex 1.4.3 on 12/6/17 3:55 PM */

/* Specification for Fractal tokens */

// user customisations

package fractal.syntax;
import java_cup.runtime.*;
import fractal.sys.FractalException;
import fractal.sys.FractalLexerException;

// JFlex directives
    

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/6/17 3:55 PM from the specification file
 * <tt>FractalLexer.jflex</tt>
 */
public class FractalLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\2\1\2\1\10\1\0\1\2\1\1\22\0\1\2\1\50"+
    "\3\0\1\13\2\0\1\14\1\15\1\12\1\11\1\16\1\4\1\5"+
    "\1\7\12\3\1\53\1\0\1\20\1\21\1\17\1\6\1\47\32\6"+
    "\1\51\1\0\1\52\1\0\1\6\1\0\1\22\1\32\1\33\1\24"+
    "\1\36\1\30\1\40\1\41\1\37\1\6\1\34\1\35\1\44\1\23"+
    "\1\25\1\42\1\6\1\26\1\45\1\27\1\43\1\46\1\31\3\6"+
    "\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\15\6\1\21\1\22\1\23\1\24\1\25"+
    "\1\0\2\26\1\27\3\6\1\30\1\31\2\6\1\32"+
    "\3\6\1\33\1\6\1\34\3\6\1\35\1\6\1\36"+
    "\2\6\1\37\1\40\1\41\11\6\1\42\13\6\1\43"+
    "\2\6\1\44\1\45\5\6\1\46\1\6\1\47\1\50"+
    "\4\6\1\51\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\54\0\54\0\130\0\204\0\260\0\334"+
    "\0\u0108\0\204\0\54\0\54\0\54\0\54\0\54\0\54"+
    "\0\54\0\54\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210"+
    "\0\u023c\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\54"+
    "\0\54\0\54\0\54\0\54\0\260\0\204\0\260\0\u0370"+
    "\0\u039c\0\u03c8\0\u03f4\0\334\0\334\0\u0420\0\u044c\0\334"+
    "\0\u0478\0\u04a4\0\u04d0\0\334\0\u04fc\0\334\0\u0528\0\u0554"+
    "\0\u0580\0\334\0\u05ac\0\334\0\u05d8\0\u0604\0\334\0\334"+
    "\0\334\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738"+
    "\0\u0764\0\u0790\0\334\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c"+
    "\0\u0898\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\334\0\u09a0"+
    "\0\u09cc\0\334\0\334\0\u09f8\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8"+
    "\0\334\0\u0ad4\0\334\0\334\0\u0b00\0\u0b2c\0\u0b58\0\u0b84"+
    "\0\334\0\334";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\3\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\10"+
    "\1\30\1\10\1\31\1\32\1\10\1\33\1\34\2\10"+
    "\1\35\1\36\2\10\1\37\1\10\1\40\1\41\1\42"+
    "\1\43\1\44\57\0\1\5\1\0\1\45\51\0\1\46"+
    "\1\0\1\45\51\0\1\47\53\0\1\10\2\0\1\10"+
    "\13\0\25\10\14\0\1\50\47\0\1\10\2\0\1\10"+
    "\13\0\1\10\1\51\23\10\10\0\1\10\2\0\1\10"+
    "\13\0\3\10\1\52\21\10\10\0\1\10\2\0\1\10"+
    "\13\0\14\10\1\53\10\10\10\0\1\10\2\0\1\10"+
    "\13\0\4\10\1\54\20\10\10\0\1\10\2\0\1\10"+
    "\13\0\5\10\1\55\6\10\1\56\1\57\7\10\10\0"+
    "\1\10\2\0\1\10\13\0\2\10\1\60\1\61\1\62"+
    "\20\10\10\0\1\10\2\0\1\10\13\0\1\63\11\10"+
    "\1\64\12\10\10\0\1\10\2\0\1\10\13\0\13\10"+
    "\1\65\11\10\10\0\1\10\2\0\1\10\13\0\5\10"+
    "\1\66\6\10\1\67\10\10\10\0\1\10\2\0\1\10"+
    "\13\0\1\10\1\70\23\10\10\0\1\10\2\0\1\10"+
    "\13\0\3\10\1\71\21\10\10\0\1\10\2\0\1\10"+
    "\13\0\2\10\1\72\11\10\1\73\4\10\1\74\3\10"+
    "\10\0\1\10\2\0\1\10\13\0\1\75\13\10\1\76"+
    "\10\10\5\0\10\50\1\0\43\50\3\0\1\10\2\0"+
    "\1\10\13\0\2\10\1\77\22\10\10\0\1\10\2\0"+
    "\1\10\13\0\5\10\1\100\17\10\10\0\1\10\2\0"+
    "\1\10\13\0\6\10\1\101\16\10\10\0\1\10\2\0"+
    "\1\10\13\0\1\10\1\102\16\10\1\103\2\10\1\104"+
    "\1\10\10\0\1\10\2\0\1\10\13\0\16\10\1\105"+
    "\6\10\10\0\1\10\2\0\1\10\13\0\4\10\1\106"+
    "\20\10\10\0\1\10\2\0\1\10\13\0\1\107\24\10"+
    "\10\0\1\10\2\0\1\10\13\0\11\10\1\110\13\10"+
    "\10\0\1\10\2\0\1\10\13\0\14\10\1\111\10\10"+
    "\10\0\1\10\2\0\1\10\13\0\6\10\1\112\16\10"+
    "\10\0\1\10\2\0\1\10\13\0\2\10\1\113\22\10"+
    "\10\0\1\10\2\0\1\10\13\0\22\10\1\114\2\10"+
    "\10\0\1\10\2\0\1\10\13\0\1\10\1\115\23\10"+
    "\10\0\1\10\2\0\1\10\13\0\24\10\1\116\10\0"+
    "\1\10\2\0\1\10\13\0\13\10\1\117\11\10\10\0"+
    "\1\10\2\0\1\10\13\0\2\10\1\120\22\10\10\0"+
    "\1\10\2\0\1\10\13\0\14\10\1\121\10\10\10\0"+
    "\1\10\2\0\1\10\13\0\5\10\1\122\17\10\10\0"+
    "\1\10\2\0\1\10\13\0\17\10\1\123\5\10\10\0"+
    "\1\10\2\0\1\10\13\0\7\10\1\124\15\10\10\0"+
    "\1\10\2\0\1\10\13\0\11\10\1\125\13\10\10\0"+
    "\1\10\2\0\1\10\13\0\12\10\1\64\12\10\10\0"+
    "\1\10\2\0\1\10\13\0\1\126\24\10\10\0\1\10"+
    "\2\0\1\10\13\0\5\10\1\66\17\10\10\0\1\10"+
    "\2\0\1\10\13\0\14\10\1\127\10\10\10\0\1\10"+
    "\2\0\1\10\13\0\2\10\1\130\16\10\1\131\3\10"+
    "\10\0\1\10\2\0\1\10\13\0\14\10\1\132\10\10"+
    "\10\0\1\10\2\0\1\10\13\0\6\10\1\133\16\10"+
    "\10\0\1\10\2\0\1\10\13\0\14\10\1\134\10\10"+
    "\10\0\1\10\2\0\1\10\13\0\1\135\24\10\10\0"+
    "\1\10\2\0\1\10\13\0\3\10\1\136\21\10\10\0"+
    "\1\10\2\0\1\10\13\0\5\10\1\55\17\10\10\0"+
    "\1\10\2\0\1\10\13\0\1\137\24\10\10\0\1\10"+
    "\2\0\1\10\13\0\5\10\1\140\17\10\10\0\1\10"+
    "\2\0\1\10\13\0\4\10\1\141\20\10\10\0\1\10"+
    "\2\0\1\10\13\0\3\10\1\142\21\10\10\0\1\10"+
    "\2\0\1\10\13\0\20\10\1\74\4\10\10\0\1\10"+
    "\2\0\1\10\13\0\4\10\1\143\20\10\10\0\1\10"+
    "\2\0\1\10\13\0\5\10\1\144\17\10\10\0\1\10"+
    "\2\0\1\10\13\0\4\10\1\145\20\10\10\0\1\10"+
    "\2\0\1\10\13\0\4\10\1\146\20\10\10\0\1\10"+
    "\2\0\1\10\13\0\1\147\24\10\10\0\1\10\2\0"+
    "\1\10\13\0\7\10\1\150\15\10\10\0\1\10\2\0"+
    "\1\10\13\0\14\10\1\151\10\10\10\0\1\10\2\0"+
    "\1\10\13\0\2\10\1\60\22\10\10\0\1\10\2\0"+
    "\1\10\13\0\13\10\1\152\11\10\10\0\1\10\2\0"+
    "\1\10\13\0\1\10\1\72\23\10\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2992];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\6\1\10\11\15\1\5\11\1\0\105\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol mkSymbol(int id) {
        return new Symbol(id, yyline, yycolumn);
    }

    private Symbol mkSymbol(int id, Object val) {
        return new Symbol(id, yyline, yycolumn, val);
    }

    public int getChar() {
	return yychar + 1;
    }

    public int getColumn() {
    	return yycolumn + 1;
    }

    public int getLine() {
	return yyline + 1;
    }

    public String getText() {
	return yytext();
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FractalLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public FractalLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 122) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, FractalException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { return mkSymbol(sym.RPAREN);
          }
        case 43: break;
        case 13: 
          { return mkSymbol(sym.COMMA);
          }
        case 44: break;
        case 21: 
          { return new Symbol(sym.COLON);
          }
        case 45: break;
        case 32: 
          { return mkSymbol(sym.NOT);
          }
        case 46: break;
        case 31: 
          { return mkSymbol(sym.AND);
          }
        case 47: break;
        case 38: 
          { return mkSymbol(sym.CLR);
          }
        case 48: break;
        case 7: 
          { return mkSymbol(sym.DIV);
          }
        case 49: break;
        case 1: 
          { // Unknown token (leave this in the last position)
    			  throw new FractalLexerException(yytext(), getLine(),
							  getColumn());
          }
        case 50: break;
        case 33: 
          { return new Symbol(sym.DEF);
          }
        case 51: break;
        case 40: 
          { return new Symbol(sym.REP);
          }
        case 52: break;
        case 42: 
          { return new Symbol(sym.FRACTAL);
          }
        case 53: break;
        case 10: 
          { return mkSymbol(sym.MOD);
          }
        case 54: break;
        case 3: 
          { // skip whitespace
          }
        case 55: break;
        case 27: 
          { return mkSymbol(sym.BK);
          }
        case 56: break;
        case 41: 
          { return new Symbol(sym.REST);
          }
        case 57: break;
        case 25: 
          { return mkSymbol(sym.RIGHT);
          }
        case 58: break;
        case 28: 
          { return mkSymbol(sym.LEFT);
          }
        case 59: break;
        case 39: 
          { return new Symbol(sym.REN);
          }
        case 60: break;
        case 19: 
          { return new Symbol(sym.LBRACE);
          }
        case 61: break;
        case 35: 
          { return mkSymbol(sym.HM);
          }
        case 62: break;
        case 11: 
          { return mkSymbol(sym.LPAREN);
          }
        case 63: break;
        case 23: 
          { // skip line comments
          }
        case 64: break;
        case 6: 
          { // IDENTIFIERS
	       		 return mkSymbol(sym.ID, yytext());
          }
        case 65: break;
        case 37: 
          { return new Symbol(sym.SELF);
          }
        case 66: break;
        case 22: 
          { // DOUBLE
	       		 return mkSymbol(sym.REAL, 
			 	         new Double(yytext()));
          }
        case 67: break;
        case 14: 
          { return mkSymbol(sym.GREAT);
          }
        case 68: break;
        case 16: 
          { return mkSymbol(sym.EQUAL);
          }
        case 69: break;
        case 18: 
          { return new Symbol(sym.SEQUENCE);
          }
        case 70: break;
        case 9: 
          { return mkSymbol(sym.MUL);
          }
        case 71: break;
        case 26: 
          { return mkSymbol(sym.FD);
          }
        case 72: break;
        case 8: 
          { return mkSymbol(sym.PLUS);
          }
        case 73: break;
        case 15: 
          { return mkSymbol(sym.LESS);
          }
        case 74: break;
        case 34: 
          { return new Symbol(sym.END);
          }
        case 75: break;
        case 24: 
          { return mkSymbol(sym.OR);
          }
        case 76: break;
        case 29: 
          { return mkSymbol(sym.PD);
          }
        case 77: break;
        case 5: 
          { return mkSymbol(sym.MINUS);
          }
        case 78: break;
        case 30: 
          { return mkSymbol(sym.PU);
          }
        case 79: break;
        case 36: 
          { return new Symbol(sym.SAVE);
          }
        case 80: break;
        case 20: 
          { return new Symbol(sym.RBRACE);
          }
        case 81: break;
        case 4: 
          { // INTEGER
	       		 return mkSymbol(sym.INT, 
			 	         new Integer(yytext()));
          }
        case 82: break;
        case 2: 
          { //skip newline
          }
        case 83: break;
        case 17: 
          { return new Symbol(sym.COMPOSE);
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 	return new Symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
