
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 06 15:55:41 GMT 2017
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREAT = 15;
  public static final int REP = 7;
  public static final int REN = 4;
  public static final int PD = 36;
  public static final int LPAREN = 12;
  public static final int INT = 37;
  public static final int LESS = 16;
  public static final int MINUS = 25;
  public static final int RPAREN = 13;
  public static final int NOT = 22;
  public static final int AND = 20;
  public static final int OR = 21;
  public static final int COMMA = 14;
  public static final int DIV = 27;
  public static final int PLUS = 24;
  public static final int FD = 31;
  public static final int ID = 39;
  public static final int FRACTAL = 2;
  public static final int LEFT = 29;
  public static final int EOF = 0;
  public static final int EQUAL = 17;
  public static final int error = 1;
  public static final int SELF = 8;
  public static final int MUL = 26;
  public static final int CLR = 33;
  public static final int MOD = 28;
  public static final int REAL = 38;
  public static final int BK = 32;
  public static final int HM = 35;
  public static final int COLON = 23;
  public static final int REST = 6;
  public static final int LBRACE = 18;
  public static final int COMPOSE = 10;
  public static final int SAVE = 5;
  public static final int RBRACE = 19;
  public static final int END = 9;
  public static final int DEF = 3;
  public static final int SEQUENCE = 11;
  public static final int RIGHT = 30;
  public static final int PU = 34;
}

